### PR TITLE
remove nvm rule

### PR DESCRIPTION
**Pull request by austinpray**

### CODE REVIEW

**Comment by lblackburn** [comment]
nah

**Comment by lblackburn** [comment]
make a pr for adding no text to #selfie tho

**Comment by DarrenCattle** [comment]
nvm could also mean node version manager gg

**Comment by austinpray** [comment]
https://github.com/austinpray/teamayylmao-bylaws#21-selfie-is-for-selfies

**Comment by austinpray** [comment]
@DarrenCattle what's your vote

**Comment by austinpray** [comment]
yee

**Comment by austinpray** [comment]
@ridhoq @ThomasLaPiana and we will have quorum

**Comment by ridhoq** [comment]
lol can I abstain?

**Comment by austinpray** [comment]
@ridhoq yes but then someone else will have to vote to keep quorum. @shermm vote pls

**Comment by austinpray** [comment]
too slow

**Pull request merged**
