### PR TITLE
Adds decision making

### PR DESCRIPTION
**Pull request by austinpray**

### CODE REVIEW

**Comment by lblackburn** [comment]
(y)

**Comment by austinpray** [comment]
(yee)

**Comment by lblackburn** [comment]
yee

**Comment by austinpray** [comment]
@darrencattle @ridhoq @ThomasLaPiana and we will have Quorum

**Comment by ridhoq** [comment]
There needs to be some sort of hierarchy for team leader. As in, if team leader isn't present, then someone stands in.

**Comment by austinpray** [comment]
Who is vice-president?

**Comment by DarrenCattle** [comment]
#VP

**Comment by austinpray** [comment]
Darren is VP

**Pull request merged**
